name: Publish GitHub Packages
on: push
jobs:
    publish-github-packages:
        name: Publish GitHub Packages
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
        - uses: actions/checkout@v3
        - uses: cachix/install-nix-action@v18
          with:
              github_access_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build with Nix
          run: nix build .#saysthbot-reborn-docker
        - name: Log in to GitHub Packages
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        - name: Push Image to GitHub Packages
          run: |
              docker load -i result
              NAME=ghcr.io/${{ github.repository_owner }}/saysthbot-reborn:latest
              docker tag saysthbot-reborn:latest $NAME
              docker push $NAME
        - name: Cross Build aarch64 Image
          run: |
              nix build .#pkgsCross.aarch64-multiplatform.saysthbot-reborn-docker
              docker load -i result
              NAME=ghcr.io/${{ github.repository_owner }}/saysthbot-reborn:latest-arm
              docker tag saysthbot-reborn:latest $NAME
              docker push $NAME
